# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Linux Application

on:
  workflow_call:
      secrets:
        envPAT:
          required: true
          
env:
  ENV_FILE_PATH: ./application/sourcefiles/telegram/environments.py

jobs:
      
  build_linux:
      name: Build Linux App
      runs-on: ubuntu-latest
    
      steps:
        - run: echo "Build Linux was triggered from <release.yml>."
        - name: Clone GitHub Repository
          uses: actions/checkout@v3
        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: Syncogram-Linux
            path: ./craft/Syncogram